const projects = {
  PureBank: {
    title: 'PureBank',
    URL: 'https://isaagverdiev.github.io/PureBank/',
    repositories: 'https://github.com/IsaAgverdiev/PureBank',
    discr: 'Лэндинг банка, для продажи Дебетовой карты',
    task: 'Необходимо было разработать дизайн макет и сверсать сайт, для оформление карты банка',
    work: [
      'Разработан дизайн макет',
      'Выполнена семантическая, адаптивная кросбраузерная верстка',
      'Написан калькулятор ипотеки',
      'Написан калькулятор кредита',
      'Написан калькулятор вкдала',
      'Работа с API добавление на сайт курса валют',
      'Форма оформления карты',
    ],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm', 'Vanilla-tilt'],
    status: 'в разработке',
  },
  Shirogo: {
    title: 'Shirogo',
    URL: 'https://isaagverdiev.github.io/Shirogo/',
    repositories: 'https://github.com/IsaAgverdiev/Shirogo',
    discr: 'Многостраничный сайт для стримера на Twitch для введения статистики ивентов и информации по стримам.',
    task: 'Необходим был сайт для хранение и предоставлении инфомрации для подписчиков и зрителей стрима',
    work: [
      'Разработан дизайн макет и сверстаны 4 странцы с двумя модальными окнами',
      'Выполнена семантическая, адаптивная кросбраузерная верстка',
      'Написан скрипт двух связянных селектов, которые выводят нужный блока с информацией',
      'Написан скрипт кастомных радиокнопок',
      'Написаны скрипты для модальных окон',
    ],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm', 'jQuery', 'Slick-slider'],
    status: 'завершен',
  },
  MyOffice: {
    title: 'MyOffice',
    URL: 'https://isaagverdiev.github.io/MyOffice/',
    repositories: 'https://github.com/IsaAgverdiev/MyOffice',
    discr: 'Лэндинг для компании по аренде и продаже офисов в БЦ на Тульской',
    task: 'Нужен сайт для продажи/аренды офисов в одном бизнес центре.',
    work: [
      'Разработан дизайн, с учетом того что компания занимается недвижемостью было принятно решение о использовании прямых углов в дизайне и фирменного синего цвета',
      'Выполнена семантическая, адаптивная кросбраузерная верстка',
      'Подключение попапа обратной связи с помощью плагина Magnific Popup',
      'Написан скрип для бургер меню',
    ],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm', 'jQuery', 'Magnific Popup'],
    status: 'завершен',
  },
  ResumeWebsite: {
    title: 'ResumeWebsite',
    URL: 'https://isaagverdiev.github.io/ResumeWebsite/',
    repositories: 'https://github.com/IsaAgverdiev/ResumeWebsite',
    discr: 'Сайт резюме для себя',
    task: 'Нужен дизайн и верстка сайта резюме для выделение на фоне других кандитатов при отклике на вансии',
    work: [
      'Разработан дизайн макет',
      'Написан скрипт-шаблонизатор для формирования html структуры проектов в портфолио',
      'Подключение и настройка плагина WinBox.js',
      'Была выполнена валидная, кроссбраузерная верстка',
      'Адаптивная верстка на основе медиа-запросов на мобильные экраны.',
    ],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm', 'WinBox.js'],
    status: 'завершен',
  },
  Desire: {
    title: 'Desire',
    URL: 'https://isaagverdiev.github.io/Desire/',
    repositories: 'https://github.com/IsaAgverdiev/Desire',
    discr: 'Многостраничный сайт дизайнерской мебели',
    task: 'Нужно сверстать многостраничный сайт',
    work: [
      'Была выполнена валидная, кроссбраузерная верстка 6 страниц',
      'Адаптивная верстка на основе медиа-запросов на мобильные экраны.',
      'Подключение и настройка плагинов slisk-slider, fancybox, mixitup',
      'написание скрипта бокового меню',
    ],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm', 'jQuery', 'slick-slider', 'fancybox', 'mixitup'],
    status: 'завершен',
  },
  KoreaCrem: {
    title: 'KoreaCrem',
    URL: 'https://isaagverdiev.github.io/KoreanCrem/',
    repositories: 'https://github.com/IsaAgverdiev/KoreanCrem',
    discr: 'Интернет-магазин корейской комсметики',
    task: 'Нужно сверстать по готовому дизайн-макету',
    work: ['Сверстана главная страница'],
    tools: ['Html', 'Css', 'Scss', 'Gulp', 'JavaScript', 'Git', 'npm'],
    status: 'в разработке',
  },
};
